# Generated by Django 6.1 on 2026-08-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
