# Generated by Django 6.1 on 2026-08-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailReport',
        ),
    ]
