# Generated by Django 6.1 on 2026-09-04 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_delete_emailreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=9, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
